### ISSUE TITLE
No module named `quart.worker`

### ISSUE THREAD

**Issue by bhushanbrb** [pgjones/faster_than_flask_article#1]
Error: class uri 'quart.worker.GunicornUVLoopWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 135, in load_class
    mod = import_module('.'.join(components))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'quart.worker'

**Comment by pgjones** [comment]
The code in this repository on works with Quart < 0.7.0. Sorry, I don't plan to update this code.
